### PR TITLE
Raise events for grow and shrink actions

### PR DESCRIPTION
**Pull request by michael-martin**
This change means that when autogrow grows/shrinks a textarea, it will then dispatch events to indicate this (Event won't fire until animation is complete, if the user has animation enabled). I've added some docs to the readme, but the code is pretty straightforward. 

It means the user's app can keep track of what's going on and update as appropriate.

As an example, my app has a textarea at the bottom of the screen, and when the box grows, I want to auto-scroll the browser down so that the full box is still visible.

What do you think?

It would also solve this issue: https://github.com/ultimatedelman/autogrow/issues/8

(Haven't updated the .min or json files btw)

PS - Thanks for making this plugin, it's been so useful!

### CODE REVIEW

**Comment by zedtux** [comment]
@michael-martin awesome ! I'm looking for that feature ! It looks like there are conflicts, can you please update your branch so that @ultimatedelman could merge it :)

**Comment by michael-martin** [comment]
@zedtux - Sorry, but the PR has been here for 2 years, I don't think it's getting merged :(

**Comment by zedtux** [comment]
Thank you @michael-martin for your message. Anyway I had to use another plugin as this one is not playing well with a `max-height` on the `textarea`.
But thanks to you as I've inspired from your code in order to implement the event triggering in the other library.

**Comment by michael-martin** [comment]
@zedtux - Ah awesome, what was the other library?

**Comment by zedtux** [comment]
[Autogrow-Textarea](http://www.technoreply.com/autogrow-textarea-plugin-3-0) by @jevin (GH: https://github.com/jevin/Autogrow-Textarea).

**Comment by michael-martin** [comment]
Cool, thanks for sharing, will check it out!

**Comment by ultimatedelman** [comment]
Hey guys, thanks for bringing this back up. I completely forgot about this pull request. Right now it's showing that the branch has conflicts. If they get resolved, I will merge.

**Comment by michael-martin** [comment]
@ultimatedelman - Sorry, slow response again here! Updated to resolve the merge issues now, thanks :)

**Pull request merged**
